version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
  app:
    stdin_open: true   # -i
    tty: true          # -t
    build:
       context: ../report_service/report_client
       dockerfile: $PWD/report_client/Dockerfile
    ports:
      - "8000:8000"
